### création log
POST http://localhost:4010/api/logs
Content-Type: application/json

{
  "level":"info",
  "message": "coucou je suis un test",
  "service": "test"
}

### récupération logs
GET http://localhost:4010/api/logs?endDate=2026-03-18&limit=2&offset=3

### récupération log par id
GET http://localhost:4010/api/logs/69b91bd27121891eaa8bb96d

###
POST http://localhost:4010/api/logs/batch
Content-Type: application/json

{
  "logs": [
    {
      "level":"info",
      "message": "coucou je suis un test",
      "service": "oquiz-api"
    },
    {
      "level":"info",
      "message": "coucou je suis un second test",
      "service": "oquiz-api"
    }
  ]
}

### Récupération des stats
GET http://localhost:4010/api/logs/stats